#title: Org Capture Presentation




emacs: 31.0.50
os: Linux Mint Debian Edition 6.1
fecha: 23 March 2025
author: no-control-to-edit



* Capturar una nota rápidamente

Esta libraria provee una manera de grabar una nota, con la mínima
interrupción del flujo.

Lo uso para notar cosas que me gustaría mejorar en emacs, cuando no
puedo hacerlo en el momento.

* Configurar una plantilla de captura (template)

  Para cada tipo de captura tienes que crear una plantilla que
  contiene la siguiente infomación.

   1. Una descripción de la plantilla
   2. Tipo de entrada
      'entry' crea un heading (titualar) de org-mode
   3. Datos usado para ubicar la entrada
   4. Cadena de formato por la entrada

   Manual de plantillas - Las varias opciones
   https://orgmode.org/manual/Template-elements.html

* Ejemplo de una plantilla
   
#+begin_src emacs-lisp  :results silent
       ("Yak Shaving en Emacs"
	entry
	(file "~/tmp/yak-shaving.org")
	"* %?")
#+end_src

* Asociar plantilla con una letra

#+begin_src emacs-lisp :results silent
  ("e" . ("Yak Shaving en Emacs"
  	entry
  	(file "~/tmp/yak-shaving.org")
  	"* %?"))
#+end_src

* Ańadir la plantilla a la lista de plantillas

#+begin_src emacs-lisp :results silent
    (setq org-capture-templates
  	'(("e" . ("Yak Shaving en Emacs"
  		  entry
  		  (file "~/tmp/yak-shaving.org")
  		  "* %?"))))
#+end_src

* Capture una nota

#+begin_src emacs-command
  M-x org-capture
#+end_src

* Visitar el archivo de notas por nombre del archivo

#+begin_src emacs-lisp :results silent
  (find-file "~/tmp/yak-shaving.org")
#+end_src

* Visitar el archivo de notas por letra

Código elisp para ir al archivo asociado con una plantilla con la
letra e

#+begin_src emacs-lisp  :results silent
(org-capture-goto-target "e")
#+end_src

nota: Cuando se usa funciones de org-capture, en vez de comandos, la
libraría no se carga automáticamente. Tienes que hacerlo manualmente.

#+begin_src emacs-lisp :results silent 
  (require 'org-capture)
#+end_src

* Añadir un org capture por letra directamente

Código elisp para activar org-capture por plantilla con letra e.

#+begin_src emacs-lisp :results silent
  (defun org-capture-e-ncte ()
    "Captura de org por plantilla e"
    (interactive)
    (org-capture nil "e"))
#+end_src

Invocarlo directamente

#+begin_src emacs-lisp :results silent
  M-x org-capture-e-ncte
#+end_src

* Añade un TODO al enacabezado

#+begin_src emacs-lisp :results silent
  (setq org-capture-templates
	'(("e" . ("Yak Shaving en Emacs"
		  entry
		  (file "~/tmp/yak-shaving.org")
		  "* TODO %?")))))))
#+end_src

* Añade la fecha actual a la entrada

#+begin_src emacs-lisp :results silent
  (setq org-capture-templates
	'(("e" . ("Yak Shaving en Emacs"
		  entry
		  (file "~/tmp/yak-shaving.org")
		  "* TODO %? %u"))))
#+end_src

* Añade la fecha en un cajón de propiedades

#+begin_src emacs-lisp :results silent
  (setq org-capture-templates
	'(("e" . ("Yak Shaving en Emacs"
		  entry
		  (file "~/tmp/yak-shaving.org")
		  "* TODO %? \n:PROPERTIES:\n:CREATED: %u\n:END:"))))
#+end_src

* Anteponer la entrada al inicio del archivo

#+begin_src emacs-lisp :results silent
  (setq org-capture-templates
	'(("e" . ("Yak Shaving en Emacs"
		entry
		(file "~/tmp/yak-shaving.org")
		"* TODO %? \n:PROPERTIES:\n:CREATED: %u\n:END:"
		:prepend t))))
#+end_src

* Abre org-mode con las entradas cerradas

#+begin_src emacs-lisp :results silent
  (setq org-startup-folded t)
#+end_src

* Copiar la region elegida a la captura

#+begin_src emacs-lisp :results silent
  (setq org-capture-templates
	'(("e" . ("Yak Shaving en Emacs"
		entry
		(file "~/tmp/yak-shaving.org")
		"* TODO %? \n:PROPERTIES:\n:CREATED: %u\n:END:\n\n%i"
		:prepend t))))
#+end_src

* Ańade un enlace a la ubicación actual

#+begin_src :results silent 
    %a
#+end_src



