* Emacs - No hay función borrar-este-archivo

  Es mejor usar dired para:
    - borrar-este-archivo
    - renombrar-este-archivo
    - copiar-este-archivo

  C-x C-j  Abre editor de directorios y archivos  (dired-jump)
  R - renombrar archivo  (dired-do-rename)
  > nombre-nuevo
  RET
  q - escapar dired  (quit-window)

  Aunque mi modo favorito es

  C-x C-j (dired-jump)
  M-x wdired-change-to-wdired-mode
  
* Voy a usar evil

Prefiero los atajos de Vim. Evil provee funcionalidad útil que está disponible en el editor Vim.

#+begin_src elisp
  (use-package evil
    :ensure t
    :config
    (evil-mode 1))
#+end_src


* Amigo español número 2


 Acabo de recibir una solicitud de amistad a través de mi página de
 [[https://github.com/nocontroltoedit/emacs-con-nocontroltoedit/tree/main][github]]. Hola Byron.



* Tengo un amigo hispano que habla de emacs

   Sebastián Monía y yo intercambiamos screencasts de nosotros usando
   emacs.

   
   Su sitio web es [[https://site.sebasmonia.com/]] y aquí es su [[https://github.com/sebasmonia][github]].

   
* Acabo de usar org-publish para generar html

¡Qué flipa, tío! Puedo publicar una página web con poca configuración

#+begin_src emacs-lisp
  (use-package ox-publish)

  (setq nocontroltoedit-github-footer "nocontroltoedit 2025")

  (add-to-list 'org-publish-project-alist
  	     '("nocontroltoedit-github-site"
  	       :base-directory "~/wd-x1/emacs-con-nocontroltoedit/docs/org"
  	       :publishing-directory "~/wd-x1/emacs-con-nocontroltoedit/docs"
      	       :publishing-function org-html-publish-to-html
  	       :html-postamble nocontroltoedit-github-footer
  	       :recursive t))
#+end_src

#+begin_src emacs-command
  M-x org-publish-current-project
#+end_src

*advertencia:* No actualiza cuando el config ha cambiado y los otros
archivos no. Usa este commando para forzar una actualización

#+begin_src emacs-command
C-u M-x org-publish-current-project
#+end_src


* Bienvenido a mi blog sobre emacs.

[[./about.org][Acepto]] correciones en mi uso de español.




