* Org-capture

  [[https://youtu.be/9z0-sZzXKDw?si=llRxmRIxOi0VOpbF][youtube - org-capture de emacs en español]]

* Emacs - No hay función borrar-este-archivo

  Es mejor usar dired para:
    - borrar archivo actual
    - renombrar archivo actual
    - copiar archivo actual

  Ejemplo de renombrar archivo usando dired   

#+begin_quote 
  ;; Abrir el editor de directorios y archivos   (dired-jump)
  C-x C-j

  ;; Renombrar el archivo bajo cursor            (dired-do-rename)
  R
  
  ;; Entra un nobmre nuevo

  ;; Aceptar los cambios
  RET

  ;; Cerrar el editor de directorios y archivos   (quit-window)
  q
#+end_quote

    Aunque mi modo favorito es

 #+begin_quote
  ;; Saltar a dired, con el foco en el archivo actual
  C-x C-j                              (dired-jump)

  ;; Hacer dired editable 
  M-x wdired-change-to-wdired-mode

  ;; editar dired como era un archivo de texto
  
  ;; Confirmar los cambios y salir
  C-c C-c                              (wdired-finish-edit)

  ;; Deshacer los cambios y salir
  C-c C-k                              (wdired-abort-changes)
 #+end_quote
  
* Voy a usar evil

Prefiero los atajos de Vim. Evil provee funcionalidad útil que está disponible en el editor Vim.

#+begin_src elisp
  (use-package evil
    :ensure t
    :config
    (evil-mode 1))
#+end_src


* Amigo español número 2


 Acabo de recibir una solicitud de amistad a través de mi página de
 [[https://github.com/nocontroltoedit/emacs-con-nocontroltoedit/tree/main][github]]. Hola Byron.



* Tengo un amigo hispano que habla de emacs

   Sebastián Monía y yo intercambiamos screencasts de nosotros usando
   emacs.

   
   Su sitio web es [[https://site.sebasmonia.com/]] y aquí es su [[https://github.com/sebasmonia][github]].

   
* Acabo de usar org-publish para generar html

¡Qué flipa, tío! Puedo publicar una página web con poca configuración

#+begin_src emacs-lisp
  (use-package ox-publish)

  (setq nocontroltoedit-github-footer "nocontroltoedit 2025")

  (add-to-list 'org-publish-project-alist
  	     '("nocontroltoedit-github-site"
  	       :base-directory "~/wd-x1/emacs-con-nocontroltoedit/docs/org"
  	       :publishing-directory "~/wd-x1/emacs-con-nocontroltoedit/docs"
      	       :publishing-function org-html-publish-to-html
  	       :html-postamble nocontroltoedit-github-footer
  	       :recursive t))
#+end_src

#+begin_src emacs-command
  M-x org-publish-current-project
#+end_src

*advertencia:* No actualiza cuando el config ha cambiado y los otros
archivos no. Usa este commando para forzar una actualización

#+begin_src emacs-command
C-u M-x org-publish-current-project
#+end_src


* Bienvenido a mi blog sobre emacs.

[[./about.org][Acepto]] correciones en mi uso de español.




